---
title: Crypto History
timezone:
collections:
  posts:
    title: Posts
    output: true
  steps:
    title: Steps
    output: false
  uploads:
    title: Uploads
    output: true
  ancient:
    title: BC
    output: false
  medieval:
    output: false
  renaissance:
    output: false
  twentieth:
    output: false
  modern:
    output: false
defaults:
  - scope:
      path: ""
      type: steps
    values:
      title:
      date: 2016-09-01 00:00:00 -0700
markdown: kramdown
highlighter: rouge
lsi: false
description: Unessay for CPSC 329 W21
baseurl: "/crypto-history"
url: http://xper28.github.io
color: "#f2f2f2"
